#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "syscall_tbl.h"


syscall_tbl syscall_table[MAX_SYSCALL];

#define syscall_name(id) syscall_table[id].name
#define syscall_type(id) syscall_table[id].type
#define syscall_hook(id) syscall_table[id].hook

void register_syscall(int id,void* hook,char* type,char* name){
    strcpy(syscall_name(id),name);
    strcpy(syscall_type(id),type);
    syscall_hook(id)=hook;
}

void init_syscall_tbl(){
    memset(syscall_table,0,sizeof(syscall_tbl));
    register_syscall(0  ,NULL,"common","read"                    );
    register_syscall(1  ,NULL,"common","write"                   );
    register_syscall(2  ,NULL,"common","open"                    );
    register_syscall(3  ,NULL,"common","close"                   );
    register_syscall(4  ,NULL,"common","stat"                    );
    register_syscall(5  ,NULL,"common","fstat"                   );
    register_syscall(6  ,NULL,"common","lstat"                   );
    register_syscall(7  ,NULL,"common","poll"                    );
    register_syscall(8  ,NULL,"common","lseek"                   );
    register_syscall(9  ,NULL,"common","mmap"                    );
    register_syscall(10 ,NULL,"common","mprotect"                );
    register_syscall(11 ,NULL,"common","munmap"                  );
    register_syscall(12 ,NULL,"common","brk"                     );
    register_syscall(13 ,NULL,"64"    ,"rt_sigaction"            );
    register_syscall(14 ,NULL,"common","rt_sigprocmask"          );
    register_syscall(15 ,NULL,"64"    ,"rt_sigreturn"            );
    register_syscall(16 ,NULL,"64"    ,"ioctl"                   );
    register_syscall(17 ,NULL,"common","pread64"                 );
    register_syscall(18 ,NULL,"common","pwrite64"                );
    register_syscall(19 ,NULL,"64"    ,"readv"                   );
    register_syscall(20 ,NULL,"64"    ,"writev"                  );
    register_syscall(21 ,NULL,"common","access"                  );
    register_syscall(22 ,NULL,"common","pipe"                    );
    register_syscall(23 ,NULL,"common","select"                  );
    register_syscall(24 ,NULL,"common","sched_yield"             );
    register_syscall(25 ,NULL,"common","mremap"                  );
    register_syscall(26 ,NULL,"common","msync"                   );
    register_syscall(27 ,NULL,"common","mincore"                 );
    register_syscall(28 ,NULL,"common","madvise"                 );
    register_syscall(29 ,NULL,"common","shmget"                  );
    register_syscall(30 ,NULL,"common","shmat"                   );
    register_syscall(31 ,NULL,"common","shmctl"                  );
    register_syscall(32 ,NULL,"common","dup"                     );
    register_syscall(33 ,NULL,"common","dup2"                    );
    register_syscall(34 ,NULL,"common","pause"                   );
    register_syscall(35 ,NULL,"common","nanosleep"               );
    register_syscall(36 ,NULL,"common","getitimer"               );
    register_syscall(37 ,NULL,"common","alarm"                   );
    register_syscall(38 ,NULL,"common","setitimer"               );
    register_syscall(39 ,NULL,"common","getpid"                  );
    register_syscall(40 ,NULL,"common","sendfile"                );
    register_syscall(41 ,NULL,"common","socket"                  );
    register_syscall(42 ,NULL,"common","connect"                 );
    register_syscall(43 ,NULL,"common","accept"                  );
    register_syscall(44 ,NULL,"common","sendto"                  );
    register_syscall(45 ,NULL,"64"    ,"recvfrom"                );
    register_syscall(46 ,NULL,"64"    ,"sendmsg"                 );
    register_syscall(47 ,NULL,"64"    ,"recvmsg"                 );
    register_syscall(48 ,NULL,"common","shutdown"                );
    register_syscall(49 ,NULL,"common","bind"                    );
    register_syscall(50 ,NULL,"common","listen"                  );
    register_syscall(51 ,NULL,"common","getsockname"             );
    register_syscall(52 ,NULL,"common","getpeername"             );
    register_syscall(53 ,NULL,"common","socketpair"              );
    register_syscall(54 ,NULL,"64"    ,"setsockopt"              );
    register_syscall(55 ,NULL,"64"    ,"getsockopt"              );
    register_syscall(56 ,NULL,"common","clone"                   );
    register_syscall(57 ,NULL,"common","fork"                    );
    register_syscall(58 ,NULL,"common","vfork"                   );
    register_syscall(59 ,NULL,"64"    ,"execve"                  );
    register_syscall(60 ,NULL,"common","exit"                    );
    register_syscall(61 ,NULL,"common","wait4"                   );
    register_syscall(62 ,NULL,"common","kill"                    );
    register_syscall(63 ,NULL,"common","uname"                   );
    register_syscall(64 ,NULL,"common","semget"                  );
    register_syscall(65 ,NULL,"common","semop"                   );
    register_syscall(66 ,NULL,"common","semctl"                  );
    register_syscall(67 ,NULL,"common","shmdt"                   );
    register_syscall(68 ,NULL,"common","msgget"                  );
    register_syscall(69 ,NULL,"common","msgsnd"                  );
    register_syscall(70 ,NULL,"common","msgrcv"                  );
    register_syscall(71 ,NULL,"common","msgctl"                  );
    register_syscall(72 ,NULL,"common","fcntl"                   );
    register_syscall(73 ,NULL,"common","flock"                   );
    register_syscall(74 ,NULL,"common","fsync"                   );
    register_syscall(75 ,NULL,"common","fdatasync"               );
    register_syscall(76 ,NULL,"common","truncate"                );
    register_syscall(77 ,NULL,"common","ftruncate"               );
    register_syscall(78 ,NULL,"common","getdents"                );
    register_syscall(79 ,NULL,"common","getcwd"                  );
    register_syscall(80 ,NULL,"common","chdir"                   );
    register_syscall(81 ,NULL,"common","fchdir"                  );
    register_syscall(82 ,NULL,"common","rename"                  );
    register_syscall(83 ,NULL,"common","mkdir"                   );
    register_syscall(84 ,NULL,"common","rmdir"                   );
    register_syscall(85 ,NULL,"common","creat"                   );
    register_syscall(86 ,NULL,"common","link"                    );
    register_syscall(87 ,NULL,"common","unlink"                  );
    register_syscall(88 ,NULL,"common","symlink"                 );
    register_syscall(89 ,NULL,"common","readlink"                );
    register_syscall(90 ,NULL,"common","chmod"                   );
    register_syscall(91 ,NULL,"common","fchmod"                  );
    register_syscall(92 ,NULL,"common","chown"                   );
    register_syscall(93 ,NULL,"common","fchown"                  );
    register_syscall(94 ,NULL,"common","lchown"                  );
    register_syscall(95 ,NULL,"common","umask"                   );
    register_syscall(96 ,NULL,"common","gettimeofday"            );
    register_syscall(97 ,NULL,"common","getrlimit"               );
    register_syscall(98 ,NULL,"common","getrusage"               );
    register_syscall(99 ,NULL,"common","sysinfo"                 );
    register_syscall(100,NULL,"common","times"                   );
    register_syscall(101,NULL,"64"    ,"ptrace"                  );
    register_syscall(102,NULL,"common","getuid"                  );
    register_syscall(103,NULL,"common","syslog"                  );
    register_syscall(104,NULL,"common","getgid"                  );
    register_syscall(105,NULL,"common","setuid"                  );
    register_syscall(106,NULL,"common","setgid"                  );
    register_syscall(107,NULL,"common","geteuid"                 );
    register_syscall(108,NULL,"common","getegid"                 );
    register_syscall(109,NULL,"common","setpgid"                 );
    register_syscall(110,NULL,"common","getppid"                 );
    register_syscall(111,NULL,"common","getpgrp"                 );
    register_syscall(112,NULL,"common","setsid"                  );
    register_syscall(113,NULL,"common","setreuid"                );
    register_syscall(114,NULL,"common","setregid"                );
    register_syscall(115,NULL,"common","getgroups"               );
    register_syscall(116,NULL,"common","setgroups"               );
    register_syscall(117,NULL,"common","setresuid"               );
    register_syscall(118,NULL,"common","getresuid"               );
    register_syscall(119,NULL,"common","setresgid"               );
    register_syscall(120,NULL,"common","getresgid"               );
    register_syscall(121,NULL,"common","getpgid"                 );
    register_syscall(122,NULL,"common","setfsuid"                );
    register_syscall(123,NULL,"common","setfsgid"                );
    register_syscall(124,NULL,"common","getsid"                  );
    register_syscall(125,NULL,"common","capget"                  );
    register_syscall(126,NULL,"common","capset"                  );
    register_syscall(127,NULL,"64"    ,"rt_sigpending"           );
    register_syscall(128,NULL,"64"    ,"rt_sigtimedwait"         );
    register_syscall(129,NULL,"64"    ,"rt_sigqueueinfo"         );
    register_syscall(130,NULL,"common","rt_sigsuspend"           );
    register_syscall(131,NULL,"64"    ,"sigaltstack"             );
    register_syscall(132,NULL,"common","utime"                   );
    register_syscall(133,NULL,"common","mknod"                   );
    register_syscall(134,NULL,"64"    ,"uselib"                  );
    register_syscall(135,NULL,"common","personality"             );
    register_syscall(136,NULL,"common","ustat"                   );
    register_syscall(137,NULL,"common","statfs"                  );
    register_syscall(138,NULL,"common","fstatfs"                 );
    register_syscall(139,NULL,"common","sysfs"                   );
    register_syscall(140,NULL,"common","getpriority"             );
    register_syscall(141,NULL,"common","setpriority"             );
    register_syscall(142,NULL,"common","sched_setparam"          );
    register_syscall(143,NULL,"common","sched_getparam"          );
    register_syscall(144,NULL,"common","sched_setscheduler"      );
    register_syscall(145,NULL,"common","sched_getscheduler"      );
    register_syscall(146,NULL,"common","sched_get_priority_max"  );
    register_syscall(147,NULL,"common","sched_get_priority_min"  );
    register_syscall(148,NULL,"common","sched_rr_get_interval"   );
    register_syscall(149,NULL,"common","mlock"                   );
    register_syscall(150,NULL,"common","munlock"                 );
    register_syscall(151,NULL,"common","mlockall"                );
    register_syscall(152,NULL,"common","munlockall"              );
    register_syscall(153,NULL,"common","vhangup"                 );
    register_syscall(154,NULL,"common","modify_ldt"              );
    register_syscall(155,NULL,"common","pivot_root"              );
    register_syscall(156,NULL,"64"    ,"_sysctl"                 );
    register_syscall(157,NULL,"common","prctl"                   );
    register_syscall(158,NULL,"common","arch_prctl"              );
    register_syscall(159,NULL,"common","adjtimex"                );
    register_syscall(160,NULL,"common","setrlimit"               );
    register_syscall(161,NULL,"common","chroot"                  );
    register_syscall(162,NULL,"common","sync"                    );
    register_syscall(163,NULL,"common","acct"                    );
    register_syscall(164,NULL,"common","settimeofday"            );
    register_syscall(165,NULL,"common","mount"                   );
    register_syscall(166,NULL,"common","umount2"                 );
    register_syscall(167,NULL,"common","swapon"                  );
    register_syscall(168,NULL,"common","swapoff"                 );
    register_syscall(169,NULL,"common","reboot"                  );
    register_syscall(170,NULL,"common","sethostname"             );
    register_syscall(171,NULL,"common","setdomainname"           );
    register_syscall(172,NULL,"common","iopl"                    );
    register_syscall(173,NULL,"common","ioperm"                  );
    register_syscall(174,NULL,"64"    ,"create_module"           );
    register_syscall(175,NULL,"common","init_module"             );
    register_syscall(176,NULL,"common","delete_module"           );
    register_syscall(177,NULL,"64"    ,"get_kernel_syms"         );
    register_syscall(178,NULL,"64"    ,"query_module"            );
    register_syscall(179,NULL,"common","quotactl"                );
    register_syscall(180,NULL,"64"    ,"nfsservctl"              );
    register_syscall(181,NULL,"common","getpmsg"                 );
    register_syscall(182,NULL,"common","putpmsg"                 );
    register_syscall(183,NULL,"common","afs_syscall"             );
    register_syscall(184,NULL,"common","tuxcall"                 );
    register_syscall(185,NULL,"common","security"                );
    register_syscall(186,NULL,"common","gettid"                  );
    register_syscall(187,NULL,"common","readahead"               );
    register_syscall(188,NULL,"common","setxattr"                );
    register_syscall(189,NULL,"common","lsetxattr"               );
    register_syscall(190,NULL,"common","fsetxattr"               );
    register_syscall(191,NULL,"common","getxattr"                );
    register_syscall(192,NULL,"common","lgetxattr"               );
    register_syscall(193,NULL,"common","fgetxattr"               );
    register_syscall(194,NULL,"common","listxattr"               );
    register_syscall(195,NULL,"common","llistxattr"              );
    register_syscall(196,NULL,"common","flistxattr"              );
    register_syscall(197,NULL,"common","removexattr"             );
    register_syscall(198,NULL,"common","lremovexattr"            );
    register_syscall(199,NULL,"common","fremovexattr"            );
    register_syscall(200,NULL,"common","tkill"                   );
    register_syscall(201,NULL,"common","time"                    );
    register_syscall(202,NULL,"common","futex"                   );
    register_syscall(203,NULL,"common","sched_setaffinity"       );
    register_syscall(204,NULL,"common","sched_getaffinity"       );
    register_syscall(205,NULL,"64"    ,"set_thread_area"         );
    register_syscall(206,NULL,"64"    ,"io_setup"                );
    register_syscall(207,NULL,"common","io_destroy"              );
    register_syscall(208,NULL,"common","io_getevents"            );
    register_syscall(209,NULL,"64"    ,"io_submit"               );
    register_syscall(210,NULL,"common","io_cancel"               );
    register_syscall(211,NULL,"64"    ,"get_thread_area"         );
    register_syscall(212,NULL,"common","lookup_dcookie"          );
    register_syscall(213,NULL,"common","epoll_create"            );
    register_syscall(214,NULL,"64"    ,"epoll_ctl_old"           );
    register_syscall(215,NULL,"64"    ,"epoll_wait_old"          );
    register_syscall(216,NULL,"common","remap_file_pages"        );
    register_syscall(217,NULL,"common","getdents64"              );
    register_syscall(218,NULL,"common","set_tid_address"         );
    register_syscall(219,NULL,"common","restart_syscall"         );
    register_syscall(220,NULL,"common","semtimedop"              );
    register_syscall(221,NULL,"common","fadvise64"               );
    register_syscall(222,NULL,"64"    ,"timer_create"            );
    register_syscall(223,NULL,"common","timer_settime"           );
    register_syscall(224,NULL,"common","timer_gettime"           );
    register_syscall(225,NULL,"common","timer_getoverrun"        );
    register_syscall(226,NULL,"common","timer_delete"            );
    register_syscall(227,NULL,"common","clock_settime"           );
    register_syscall(228,NULL,"common","clock_gettime"           );
    register_syscall(229,NULL,"common","clock_getres"            );
    register_syscall(230,NULL,"common","clock_nanosleep"         );
    register_syscall(231,NULL,"common","exit_group"              );
    register_syscall(232,NULL,"common","epoll_wait"              );
    register_syscall(233,NULL,"common","epoll_ctl"               );
    register_syscall(234,NULL,"common","tgkill"                  );
    register_syscall(235,NULL,"common","utimes"                  );
    register_syscall(236,NULL,"64"    ,"vserver"                 );
    register_syscall(237,NULL,"common","mbind"                   );
    register_syscall(238,NULL,"common","set_mempolicy"           );
    register_syscall(239,NULL,"common","get_mempolicy"           );
    register_syscall(240,NULL,"common","mq_open"                 );
    register_syscall(241,NULL,"common","mq_unlink"               );
    register_syscall(242,NULL,"common","mq_timedsend"            );
    register_syscall(243,NULL,"common","mq_timedreceive"         );
    register_syscall(244,NULL,"64"    ,"mq_notify"               );
    register_syscall(245,NULL,"common","mq_getsetattr"           );
    register_syscall(246,NULL,"64"    ,"kexec_load"              );
    register_syscall(247,NULL,"64"    ,"waitid"                  );
    register_syscall(248,NULL,"common","add_key"                 );
    register_syscall(249,NULL,"common","request_key"             );
    register_syscall(250,NULL,"common","keyctl"                  );
    register_syscall(251,NULL,"common","ioprio_set"              );
    register_syscall(252,NULL,"common","ioprio_get"              );
    register_syscall(253,NULL,"common","inotify_init"            );
    register_syscall(254,NULL,"common","inotify_add_watch"       );
    register_syscall(255,NULL,"common","inotify_rm_watch"        );
    register_syscall(256,NULL,"common","migrate_pages"           );
    register_syscall(257,NULL,"common","openat"                  );
    register_syscall(258,NULL,"common","mkdirat"                 );
    register_syscall(259,NULL,"common","mknodat"                 );
    register_syscall(260,NULL,"common","fchownat"                );
    register_syscall(261,NULL,"common","futimesat"               );
    register_syscall(262,NULL,"common","newfstatat"              );
    register_syscall(263,NULL,"common","unlinkat"                );
    register_syscall(264,NULL,"common","renameat"                );
    register_syscall(265,NULL,"common","linkat"                  );
    register_syscall(266,NULL,"common","symlinkat"               );
    register_syscall(267,NULL,"common","readlinkat"              );
    register_syscall(268,NULL,"common","fchmodat"                );
    register_syscall(269,NULL,"common","faccessat"               );
    register_syscall(270,NULL,"common","pselect6"                );
    register_syscall(271,NULL,"common","ppoll"                   );
    register_syscall(272,NULL,"common","unshare"                 );
    register_syscall(273,NULL,"64"    ,"set_robust_list"         );
    register_syscall(274,NULL,"64"    ,"get_robust_list"         );
    register_syscall(275,NULL,"common","splice"                  );
    register_syscall(276,NULL,"common","tee"                     );
    register_syscall(277,NULL,"common","sync_file_range"         );
    register_syscall(278,NULL,"64"    ,"vmsplice"                );
    register_syscall(279,NULL,"64"    ,"move_pages"              );
    register_syscall(280,NULL,"common","utimensat"               );
    register_syscall(281,NULL,"common","epoll_pwait"             );
    register_syscall(282,NULL,"common","signalfd"                );
    register_syscall(283,NULL,"common","timerfd_create"          );
    register_syscall(284,NULL,"common","eventfd"                 );
    register_syscall(285,NULL,"common","fallocate"               );
    register_syscall(286,NULL,"common","timerfd_settime"         );
    register_syscall(287,NULL,"common","timerfd_gettime"         );
    register_syscall(288,NULL,"common","accept4"                 );
    register_syscall(289,NULL,"common","signalfd4"               );
    register_syscall(290,NULL,"common","eventfd2"                );
    register_syscall(291,NULL,"common","epoll_create1"           );
    register_syscall(292,NULL,"common","dup3"                    );
    register_syscall(293,NULL,"common","pipe2"                   );
    register_syscall(294,NULL,"common","inotify_init1"           );
    register_syscall(295,NULL,"64"    ,"preadv"                  );
    register_syscall(296,NULL,"64"    ,"pwritev"                 );
    register_syscall(297,NULL,"64"    ,"rt_tgsigqueueinfo"       );
    register_syscall(298,NULL,"common","perf_event_open"         );
    register_syscall(299,NULL,"64"    ,"recvmmsg"                );
    register_syscall(300,NULL,"common","fanotify_init"           );
    register_syscall(301,NULL,"common","fanotify_mark"           );
    register_syscall(302,NULL,"common","prlimit64"               );
    register_syscall(303,NULL,"common","name_to_handle_at"       );
    register_syscall(304,NULL,"common","open_by_handle_at"       );
    register_syscall(305,NULL,"common","clock_adjtime"           );
    register_syscall(306,NULL,"common","syncfs"                  );
    register_syscall(307,NULL,"64"    ,"sendmmsg"                );
    register_syscall(308,NULL,"common","setns"                   );
    register_syscall(309,NULL,"common","getcpu"                  );
    register_syscall(310,NULL,"64"    ,"process_vm_readv"        );
    register_syscall(311,NULL,"64"    ,"process_vm_writev"       );
    register_syscall(312,NULL,"common","kcmp"                    );
    register_syscall(313,NULL,"common","finit_module"            );
    register_syscall(314,NULL,"common","sched_setattr"           );
    register_syscall(315,NULL,"common","sched_getattr"           );
    register_syscall(316,NULL,"common","renameat2"               );
    register_syscall(317,NULL,"common","seccomp"                 );
    register_syscall(318,NULL,"common","getrandom"               );
    register_syscall(319,NULL,"common","memfd_create"            );
    register_syscall(320,NULL,"common","kexec_file_load"         );
    register_syscall(321,NULL,"common","bpf"                     );
    register_syscall(322,NULL,"64"    ,"execveat"                );
    register_syscall(323,NULL,"common","userfaultfd"             );
    register_syscall(324,NULL,"common","membarrier"              );
    register_syscall(325,NULL,"common","mlock2"                  );
    register_syscall(326,NULL,"common","copy_file_range"         );
    register_syscall(327,NULL,"64"    ,"preadv2"                 );
    register_syscall(328,NULL,"64"    ,"pwritev2"                );
    register_syscall(329,NULL,"common","pkey_mprotect"           );
    register_syscall(330,NULL,"common","pkey_alloc"              );
    register_syscall(331,NULL,"common","pkey_free"               );
    register_syscall(332,NULL,"common","statx"                   );
    register_syscall(333,NULL,"common","io_pgetevents"           );
    register_syscall(334,NULL,"common","rseq"                    );
    register_syscall(424,NULL,"common","pidfd_send_signal"       );
    register_syscall(425,NULL,"common","io_uring_setup"          );
    register_syscall(426,NULL,"common","io_uring_enter"          );
    register_syscall(427,NULL,"common","io_uring_register"       );
    register_syscall(428,NULL,"common","open_tree"               );
    register_syscall(429,NULL,"common","move_mount"              );
    register_syscall(430,NULL,"common","fsopen"                  );
    register_syscall(431,NULL,"common","fsconfig"                );
    register_syscall(432,NULL,"common","fsmount"                 );
    register_syscall(433,NULL,"common","fspick"                  );
    register_syscall(434,NULL,"common","pidfd_open"              );
    register_syscall(435,NULL,"common","clone3"                  );
    register_syscall(436,NULL,"common","close_range"             );
    register_syscall(437,NULL,"common","openat2"                 );
    register_syscall(438,NULL,"common","pidfd_getfd"             );
    register_syscall(439,NULL,"common","faccessat2"              );
    register_syscall(440,NULL,"common","process_madvise"         );
    register_syscall(441,NULL,"common","epoll_pwait2"            );
    register_syscall(442,NULL,"common","mount_setattr"           );
    register_syscall(444,NULL,"common","landlock_create_ruleset" );
    register_syscall(445,NULL,"common","landlock_add_rule"       );
    register_syscall(446,NULL,"common","landlock_restrict_self"  );
    register_syscall(512,NULL,"x32"   ,"rt_sigaction"            );
    register_syscall(513,NULL,"x32"   ,"rt_sigreturn"            );
    register_syscall(514,NULL,"x32"   ,"ioctl"                   );
    register_syscall(515,NULL,"x32"   ,"readv"                   );
    register_syscall(516,NULL,"x32"   ,"writev"                  );
    register_syscall(517,NULL,"x32"   ,"recvfrom"                );
    register_syscall(518,NULL,"x32"   ,"sendmsg"                 );
    register_syscall(519,NULL,"x32"   ,"recvmsg"                 );
    register_syscall(520,NULL,"x32"   ,"execve"                  );
    register_syscall(521,NULL,"x32"   ,"ptrace"                  );
    register_syscall(522,NULL,"x32"   ,"rt_sigpending"           );
    register_syscall(523,NULL,"x32"   ,"rt_sigtimedwait"         );
    register_syscall(524,NULL,"x32"   ,"rt_sigqueueinfo"         );
    register_syscall(525,NULL,"x32"   ,"sigaltstack"             );
    register_syscall(526,NULL,"x32"   ,"timer_create"            );
    register_syscall(527,NULL,"x32"   ,"mq_notify"               );
    register_syscall(528,NULL,"x32"   ,"kexec_load"              );
    register_syscall(529,NULL,"x32"   ,"waitid"                  );
    register_syscall(530,NULL,"x32"   ,"set_robust_list"         );
    register_syscall(531,NULL,"x32"   ,"get_robust_list"         );
    register_syscall(532,NULL,"x32"   ,"vmsplice"                );
    register_syscall(533,NULL,"x32"   ,"move_pages"              );
    register_syscall(534,NULL,"x32"   ,"preadv"                  );
    register_syscall(535,NULL,"x32"   ,"pwritev"                 );
    register_syscall(536,NULL,"x32"   ,"rt_tgsigqueueinfo"       );
    register_syscall(537,NULL,"x32"   ,"recvmmsg"                );
    register_syscall(538,NULL,"x32"   ,"sendmmsg"                );
    register_syscall(539,NULL,"x32"   ,"process_vm_readv"        );
    register_syscall(540,NULL,"x32"   ,"process_vm_writev"       );
    register_syscall(541,NULL,"x32"   ,"setsockopt"              );
    register_syscall(542,NULL,"x32"   ,"getsockopt"              );
    register_syscall(543,NULL,"x32"   ,"io_setup"                );
    register_syscall(544,NULL,"x32"   ,"io_submit"               );
    register_syscall(545,NULL,"x32"   ,"execveat"                );
    register_syscall(546,NULL,"x32"   ,"preadv2"                 );
    register_syscall(547,NULL,"x32"   ,"pwritev2"                );
}

syscall_tbl* get_syscall_table(){
    return syscall_table;
}

int valid_syscall(int id){
    if(syscall_name(id))return 0;
    else return 1;
}

int info_syscall(int id){
    if(!syscall_name(id))return 1;
    printf("syscall(%03d): %24s => %16p | %s\n",
            id,syscall_name(id),syscall_hook(id),syscall_type(id)
            );
    return 0;
}


/* test
int main(){
    init_syscall_tbl();
    info_syscall(0);
    return 0;
}
*/